### ISSUE TITLE
Add needrestart support

### ISSUE THREAD

**Issue by linuxmail** [robertdebock/ansible-role-reboot#5]
**Is your feature request related to a problem? Please describe.**
We installed on all Debian hosts "[needrestart](https://github.com/liske/needrestart)" which gives you a nice terminal gui, which services you want to restart. It tells you also, if a system needs a reboot.

**Describe the solution you'd like**
I would like to have support for the command "[needrestart](https://github.com/liske/needrestart/blob/master/README.batch.md)", to get, if the system requires a reboot:

```
needrestart -b | grep 'NEEDRESTART-KSTA: 3'
NEEDRESTART-KSTA: 3
```
> 

The kernel status (NEEDRESTART-KSTA) value has the following meaning:

    0: unknown or failed to detect
    1: no pending upgrade
    2: ABI compatible upgrade pending
    3: version upgrade pending

**Describe alternatives you've considered**
we dropped the old command needs-restart, to not have two tools for the same.

**Comment by robertdebock** [comment]
Okay, that sounds like a logical thing to build in. I'll have a look and propose a change.

Thanks @linuxmail!

**Comment by robertdebock** [comment]
Hi Denny, can you take a look at [this proposed changed](https://github.com/robertdebock/ansible-role-reboot/tree/issue-5-add-needsrestart-support) to see if it would suit your needs?

Regards,

Robert.

**Comment by linuxmail** [comment]
hi @robertdebock 

your version works much better then my Grep version :-)  Its very cool.

Do I assume right, that a "kernel change", always do an reboot, also if update_reboot = no ? But anyway, the change works.

Thanks so much !
